services:
  yocdock:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yocdock
    volumes:
      - type: bind
        source: ${SRC_DIR}
        target: /yocto
volumes:
  yocto:
    driver: local