services:
  yocdock:
    platform: linux/x86_64
    build:
      context: ./dockerfiles
      dockerfile: yoctorun.dockerfile
    volumes:
      - type: bind
        source: ${SRC_DIR}
        target: /yocto
volumes:
  yocto:
    driver: local