services:
  yocdock-dev:
    image: crops/toaster:latest
    ports:
      - "18000:8000" # Toaster web interface on port 18000
    volumes: # Mount the Yocto build directory specified in .env
      - type: bind
        source: ${SRC_DIR}
        target: /workdir
    stdin_open: true # docker run -i
    tty: true # docker run -t
  yocdock-build:
    build:
      context: ../dockerfiles
      dockerfile: yoctobuild.dockerfile
    volumes:
      - type: bind
        source: ${SRC_DIR}
        target: /workdir
volumes:
  yocto:
    driver: local